repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/pycqa/flake8
    rev: "7.1.0"
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
    -   id: mypy
        args: [--disallow-untyped-defs, --ignore-missing-imports]
        additional_dependencies: ['types-PyYAML', 'types-toml', 'types-requests', 'types-cachetools']
-   repo: https://github.com/jazzband/pip-tools
    rev: 7.4.1
    hooks:
      - id: pip-compile
        name: pip-compile pyproject.toml main
        args:
          [
            "--verbose",
            "--upgrade",
            "--output-file",
            "pyproject.lock",
            "pyproject.toml",
          ]
        files: ^(pyproject\.toml|pyproject\.lock)$
-     repo: https://github.com/pypa/pip-audit
      rev: v2.7.3
      hooks:
        - id: pip-audit
          name: pip-audit main lock
          args: ["--requirement", "pyproject.lock",]
