# https://taskfile.dev

version: '3'

dotenv:
  - '.env'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  print-env:
    cmds:
      - echo "BOT_TOKEN=$BOT_TOKEN"
      - echo "GROUP_ID=$GROUP_ID"
    silent: true

  prc:
    cmds:
      - pre-commit run --all-files
    silent: true

  build:
    cmds:
      - docker build -f Dockerfile -t theatres .

  run:
    cmds:
      - docker run --env-file .env theatres
